### ISSUE TITLE
Can't connect to Gmail SMTP with TLS enabled

### ISSUE THREAD

**Issue by devops-cora** [gocd-contrib/email-notifier#82]
We are receiving this error to connect with smtp.gmail.com:

No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

There something wrong in my configuration?

![gocd_smtp_config](https://user-images.githubusercontent.com/65297093/208488588-c0764cdc-8783-44cb-becc-493199a27c1d.png)
```

 javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587
jvm 1    | 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
jvm 1    | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
jvm 1    | 	at javax.mail.Service.connect(Service.java:295)
jvm 1    | 	at com.tw.go.plugin.SMTPMailSender.send(SMTPMailSender.java:46)
jvm 1    | 	at com.tw.go.plugin.EmailNotificationPluginImpl.handleStageNotification(EmailNotificationPluginImpl.java:157)
jvm 1    | 	at com.tw.go.plugin.EmailNotificationPluginImpl.handle(EmailNotificationPluginImpl.java:93)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:83)
jvm 1    | 	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:44)
jvm 1    | 	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:29)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
jvm 1    | 	at java.base/sun.security.ssl.HandshakeContext.<init>(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.TransportContext.kickstart(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
jvm 1    | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
jvm 1    | 	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:354)
jvm 1    | 	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:237)
jvm 1    | 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
jvm 1    | 	... 16 common frames omitted
```

Thank you

**Comment by chadlwilson** [comment]
I generally wouldn't recommend enabling old (insecure) TLS algorithms, but all the same it'd be good to understand what GoCD and/or Java version people were using when they got this error.

**Comment by klinux** [comment]
Hello @chadlwilson we are using the last version gocd 22.3.0 official container docker, and we are receiving this error.

**Comment by chadlwilson** [comment]
Interesting, this uses an ancient javamail version from 2013, so I am not surprised it doesn't work. GoCD server has used far, far newer versions for a long time. Enabling old protocols on the Java level probably allows the mail library here to use it because it doesn't support newer versions.

Let me have a go at updating it.

**Comment by chadlwilson** [comment]
Hi folks, can one of you have a go with https://github.com/gocd-contrib/email-notifier/releases/tag/v1.2.0-169-exp

If it works fine for you I'll release it more officially.

**Comment by klinux** [comment]
The same error here:

`gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    | jakarta.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2260)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:753)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at jakarta.mail.Service.connect(Service.java:342)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.tw.go.plugin.SMTPMailSender.send(SMTPMailSender.java:55)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.tw.go.plugin.EmailNotificationPluginImpl.handleStageNotification(EmailNotificationPluginImpl.java:155)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.tw.go.plugin.EmailNotificationPluginImpl.handle(EmailNotificationPluginImpl.java:91)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:83)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:44)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:29)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/java.lang.Thread.run(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    | Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:628)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:402)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2208)
gocd-server-645cbcd9ff-wnp4z gocd-server jvm 1    |     ... 16 common frames omitted`

Here the plugin installation

gocd-server $ curl --silent --location --fail --retry 3 https://github.com/gocd-contrib/email-notifier/releases/download/v1.2.0-169-exp/email-notifier-1.2.0-169.jar --output /godata/plugins/external/email-notifier.jar

**Comment by chadlwilson** [comment]
@klinux That's a different error to the stack trace in the original message (`javax.net.ssl.SSLException: Unsupported or unrecognized SSL message` vs `javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)`). Has that changed before + after plugin versions for you?

Can you try changing it to port `465`? I believe on gmail if using STARTTLS you might have to use a different port, which may also be related to the original reporter's error.

https://developers.google.com/gmail/imap/imap-smtp

I'm not 100% sure whether Java Mail/Eclipse Angus Mail supports both STARTTLS and plain TLS for SMTP and whether we are configuring it correctly, however the plugin configuration after my change is identical to the GoCD Server. So if the GoCD server can send mail, the plugin should be able to as well (with the same configuration).

**Comment by Gavster4** [comment]
The plugin assumes tls as smtps vs starttls if it's port 25 (i don't
remember if it's explicit or implicit). My customization was to set the
smtps bits to false and always use starttls if tls is selected. It's a bit
of a story but I couldn't get another port turned up for the smtp server I
have to use for this case.

I'll try to get the new plugin version tested. I suspect the message above
is the plugin trying smtps against a starttls connection. It was one that I
ran into partway through and see if it resolves my need for the old
protocols

**Comment by chadlwilson** [comment]
@Gavster4 I don't believe the plugin assumes anything regarding ports - if you check the "tls" box in plugin settings, it **previously** (`1.1.x`) enabled both `smtps` protocol and STARTTLS - which is a bit weird, and maybe is what you were struggling with as you sound like you want STARTTLS only. I'm not sure if the logic within JavaMail allows "try to connect with TLS, if that fails, try plaintext and upgrade with STARTTLS".

I'm not sure why the plugin logic was this way, as it doesn't make sense to me to enable both `smtps` protocol and `STARTTLS`, and it's different to the GoCD server, but maybe GoCD server used to be like that historically.

`1.1` logic:
https://github.com/gocd-contrib/email-notifier/blob/5235cbd6d074175daf980b6399b4cf4bfff089df/src/main/java/com/tw/go/plugin/SMTPMailSender.java#L74-L80

Thanks for your message though, I realised that this is actually different to GoCD server (STARTTLS requires a system property opt-in there). I also accidentally reverted this behavior in my change above. I am wondering whether I should restore it or just bump the version and note a breaking change.

With the code *right now*, enabling "TLS" in options will do `smtps` and try and create a TLS socket out of the box. If you want to do STARTTLS you would leave TLS disabled in the plugin settings and probably need to set a system property on GoCD server like `-Dmail.smtp.starttls.enable=true`. This is how GoCD server works.

`1.20-169` logic:
https://github.com/gocd-contrib/email-notifier/blob/27eb607db9ba643c140ccb8a2bd699ebbafc64b5/src/main/java/com/tw/go/plugin/SMTPMailSender.java#L83-L91

I can't exactly explain @klinux 's error right now and there are likely a few different things going on here. Probably need to do some empirical testing against Gmail at some point to understand in detail since the reports so far don't include complete sets of config, GoCD server version, plugin version, java version etc.

**Comment by Gavster4** [comment]
@chadlwilson Reading the table above helped. I was assuming I needed to specify TLS in the plugin as separate mail settings from the rest of the running server. Dropping this version corrected the issue with the java.security file needing to be changed and setting the plugin TLS to no in the defaulted it back to the STARTTLS that the rest of my GoCD system was using on 25. I'll still need to recompile to put servernames in the plugin email messages but this definitely fixed both messages/issues for me. 

Looks like everyone should be golden now if they are using STARTTLS by leaving TLS as no on the plugin and setting "-Dmail.smtp.starttls.enable=true" in their wrapper config.

Thanks!
